### ISSUE TITLE
use gherkin3

### ISSUE THREAD

**Issue by ahdinosaur** [yoshuawuyts/cuke-tap#1]
related to https://github.com/yoshuawuyts/gherkin-parser/issues/1

also there's an example reference implementation of cucumber based on gherkin3: [microcuke](https://github.com/cucumber/microcuke), sharing here in case it's useful.

**Comment by yoshuawuyts** [comment]
yeah, that'd be rad!

**Comment by yoshuawuyts** [comment]
we're supporting `gherkin@4` now from npm; which should be the latest syntax. Closing for now, feel free to reopen if I'm mistaken :tada:
